### ISSUE TITLE
@Router / [post] creates panic

### ISSUE THREAD

**Issue by tobwiens** [yvasiyarov/swagger#109]
I have simple microservices which only do one operation and I let this operation happen on the root.

When I create asciidoc with a @Router / [post] I get the following panic.

```
2016/02/19 21:21:30 Start parsing
2016/02/19 21:21:31 Can not parse comment for function: HandleLoginRequest, package: tobwiens/user/handle, got error: Can not pars
e response comment "200 {object}", skipped.
2016/02/19 21:21:31 Can not parse comment for function: HandleLoginRequest, package: tobwiens/user/handle, got error: Can not pars
e response comment "400 {object}", skipped.
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/yvasiyarov/swagger/parser.(*Parser).AddOperation(0xc08204c080, 0xc089bbcb00)
        C:/Users/Toby/Go/src/github.com/yvasiyarov/swagger/parser/parser.go:185 +0x9cc
github.com/yvasiyarov/swagger/parser.(*Parser).ParseApiDescription(0xc08204c080, 0xc082008660, 0x14)
        C:/Users/Toby/Go/src/github.com/yvasiyarov/swagger/parser/parser.go:423 +0x744
github.com/yvasiyarov/swagger/parser.(*Parser).ParseApi(0xc08204c080, 0xc082008660, 0x14)
        C:/Users/Toby/Go/src/github.com/yvasiyarov/swagger/parser/parser.go:225 +0x1fa
github.com/yvasiyarov/swagger/generator.Run(0xc082008660, 0x14, 0xc082005f50, 0x2b, 0xc082002230, 0x8, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/Toby/Go/src/github.com/yvasiyarov/swagger/generator/generator.go:161 +0xb5a
main.main()
        C:/Users/Toby/Go/src/github.com/yvasiyarov/swagger/main.go:38 +0x1af
```

Cheers,
Tobias

**Comment by juanolon** [comment]
jep, just got the same error
``
github.com/yvasiyarov/swagger/parser.(*Parser).AddOperation(0xc08204c080, 0xc089bbcb00)
        C:/Users/Toby/Go/src/github.com/yvasiyarov/swagger/parser/parser.go:185 +0x9cc
``
Cheers

**Comment by yun-wang** [comment]
Got the same error with `@Router / [get]`, is there a work-around for this?
